// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrgovinaAPI.Models;

namespace TrgovinaAPI.Migrations
{
    [DbContext(typeof(IzdelekContext))]
    [Migration("20200608233631_AddIzdelkiToDb")]
    partial class AddIzdelkiToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TrgovinaAPI.Models.Izdelek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("CenaIzdelka")
                        .HasColumnType("double precision");

                    b.Property<string>("ImeIzdelka")
                        .HasColumnType("text");

                    b.Property<bool>("NaVoljo")
                        .HasColumnType("boolean");

                    b.Property<string>("OpisIzdelka")
                        .HasColumnType("text");

                    b.Property<int>("Zaloga")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Izdelki");
                });
#pragma warning restore 612, 618
        }
    }
}
